# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Setup latest .NET SDKs
        uses: Elskom/setup-latest-dotnet@v1
        with:
          VERSION_MAJOR: 6
      - name: "Update Version"
        id: updateVersion
        run: |
          rm .version
          dotnet tool install gitversion.tool -g
          dotnet-gitversion /showvariable SemVer > ./.version
          cat ./.version
          git config --global user.email "ninja@thesharp.ninja"
          git config --global user.name "GitHub on behalf of Sharp Ninja"
          git stage ./.version
          git commit -m 'Updated `.version`' --allow-empty --status
          git push --repo='https://sharpninja:${{ secrets.GITHUB_TOKEN }}@github.com/sharpninja/Snippets.git'
          echo '::set-output name=version::${version}'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.updateVersion.outputs.version }}
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}    
