# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: "Update Version"
        id: updateVersion
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          # PowerShell script to execute in Actions-hydrated context
          script: |
            dotnet tool install gitversion.tool -g
            $version = & $gitversion /showvariable SemVer
            $version | Out-File -FilePath '.version' -Encoding utf8NoBOM -force
            git add '.version'
            git commit -m "Updated `.version`"
            git push
            echo "::set-output name=version::$(cat .version)"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.updateVersion.outputs.version }}
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}    
