# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Setup latest .NET SDKs
        uses: Elskom/setup-latest-dotnet@v1
        with:
          VERSION_MAJOR: 6
      - name: "Update Version"
        id: updateVersion
        run: |
          dotnet tool install gitversion.tool -g
          version=$(dotnet-gitversion /showvariable SemVer)
          echo '$version' > ./.version
          git config --global user.email "ninja@thesharp.ninja"
          git config --global user.name "GitHub on behalf of Sharp Ninja"
          git add '.version'
          git commit -m 'Updated `.version`'
          git push --set-upstream origin master
          echo '::set-output name=version::$(cat .version)'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.updateVersion.outputs.version }}
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}    
